version: "3.7"
services:
  web:
    container_name: 'read_cv'
    build: ./docker
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./main.py
    ports:
      - 5001:5000
    volumes:
      - ./project:/app